server:
  port: ${CUSTOM.SERVER.PORT:8082}

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/BDNX1
    username: LLE
    password: YVL
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
  application:
    name: HOTEL-SERVICE